services:
  postgres:
    image: postgres:latest
    container_name: retail-billing-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billing
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  retail-billing-service:
    build: .
    container_name: retail-billing-service
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres-data:
    name: retail-billing-postgres-data
